export const API_BASE_URL = 'http://localhost:3004'

export const DIALOG_PRODUCT_CATEGORY_DELETE = 'DIALOG_PRODUCT_CATEGORY_DELETE'

export const DIALOG_PRODUCT_CATEGORY_EDIT = 'DIALOG_PRODUCT_CATEGORY_EDIT'